name = "line-crm-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

# API_KEY is set via `wrangler secret put API_KEY`
# Do NOT hardcode secrets here

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "097ec44d-c37c-4cb7-88ef-e56873369e90"

[triggers]
crons = ["*/5 * * * *"]
